apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
spec:
  servingCerts:
    namedCertificates:
      - names:
          - "api.mysite-cluster.mydomain.de"
        servingCertificate:
          name: cert-api
