apiVersion: v1
kind: Secret
metadata:
  name: cert-wildcard
  namespace: openshift-ingress
type: kubernetes.io/tls
stringData:
  tls.crt: <ENCRYPTED>
  tls.key: <ENCRYPTED>
sops:
# sops internal stuff ...
